#!/usr/bin/python3

# Python stdlib
import gettext

# 3rd Party
from PyPump.PyPump import PyPump

# Muon
from configuration import configuration
from GraphicsController import Controller

class Muon:
    def __init__(self):
        
        self.gc = Controller(self)
        
        # so do we have any accounts?
        if not configuration or True and False:
            # okay lets tell the interface to display the 
            # new account view
            self.gc.change_view("new_account")
        else:
            self.gc.change_view("message")

        while True:
            import time
            time.sleep(1)

if __name__ == "__main__":
    muon = Muon()
