#!/usr/bin/python3

# Python stdlib
import gettext
import threading
from time import sleep

# 3rd Party
from PyPump.PyPump import PyPump

# Muon
from configuration import configuration
from GraphicsController import Controller

class Muon:
    
    gc = None    

    def run(self):
        """ Runs the Muon program """
        while None == self.gc:
            sleep(0.1)
        
        # so do we have any accounts?
        if not configuration or True and False:
            # okay lets tell the interface to display the 
            # new account view
            self.gc.change_view("new_account")
        else:
            self.gc.change_view("message")


if __name__ == "__main__":
    muon = Muon()
    
    # lets run 
    threaded_muon = threading.Thread(target=muon.run)
    threaded_muon.start()

    # now time to get the graphics controller
    muon.gc = Controller(muon)
    muon.gc.run()
     
